### ISSUE TITLE
Api not providing correct information

### ISSUE THREAD

**Issue by Himanshu081** [ffardeen/cowin-vaccine-notifier#2]
Hi . I tried using your api and it is giving wrong information for slots at my pincode as i compared the results with official government information. Slot is actually available at Cowin page while in your api response slot is showing as zero at the same pincode.
 is your api updated frequently or not ??. Please have a look into this issue.

**Comment by ffardeen** [comment]
Hello. Please make sure you are entering the correct details like pin code, age (only 18 or 45), etc. The script has been tested with available slots for both 18+ and 45+.
